### ISSUE TITLE
inner layer naming different than before

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/SparkFun_KiCad_CAMmer#3]
We used to name our 4 layer boards gerbers like so: 

filename to layer stackup 1/2/3/4: GTL, GL2, GL3, GBL

Now, this cammer is naming them GTL/GL1/GL2/GBL. 

Not sure if this is a real issue. I'm sure fab houses can figure this out. But if we'd like to stay the same as before, then maybe we could consider switching back?

FWW, looks like JLC likes G2L and G3L for inner layers on a four-layer board:

[https://jlcpcb.com/help/article/233-Suggested-Naming-Patterns](https://jlcpcb.com/help/article/233-Suggested-Naming-Patterns)

**Comment by PaulZC** [comment]
Thanks Pete,

Yeah. Let's change it back. I went with GL1 and GL2 to match the KiCad names In1.Cu and In2.Cu. But let's go back to how it was and keep JLCPCB happy...

The line to change is [this one](https://github.com/sparkfun/SparkFun_KiCad_CAMmer/blob/58aa4cc683687533dbb4284153bc20178e8b256a/SparkFunKiCadCAMmer/cammer/cammer.py#L120). It needs to be ```file_ext["In{}.Cu".format(i)] = "GL{}".format(i + 1)```

Also, I should add the "layer stackup" text in ordering_instructions. That's missing too...

**Comment by PaulZC** [comment]
@lewispg228 : please give v1.0.2 a try : https://github.com/sparkfun/SparkFun_KiCad_CAMmer/actions/runs/8154619523

You will need to:
* Download the artifact
* Open the KiCad Pugin and Content Manager
* Click the "Installed" tab
* Click the CAMmer "Uninstall" button
* Click "Apply Pending Changes"
* Click "Install from File"
* Select the v1.0.2 zip file
* Close the PCM
* Open a PCB
* Give it a try!

Thanks!

**Comment by PaulZC** [comment]
PS. I didn't add the "layer stackup" text to ordering instructions. That's a small nightmare. The best place to do it is in the Panelizer, but then the Panelizer would need to be aware of the filename extensions used by the CAMmer. We'd need some kind of shared resource to do the job properly...

**Comment by PaulZC** [comment]
Resolved in v1.0.2
